//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activitati
    {
        public int idActivitate { get; set; }
        public string numeSport { get; set; }
        public System.DateTime dataa { get; set; }
        public string nrKilometrii { get; set; }
        public string nrCaloriiArse { get; set; }
        public string imagine { get; set; }
    }
}
